apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.name }}-secret
type: Opaque
data:
  mongodb-root-username: {{ .Values.mongodb.rootUsername | b64enc }}
  mongodb-root-password: {{ .Values.mongodb.rootPassword | b64enc }}
