apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongodb.service.port }}
  selector:
    app: {{ .Values.mongodb.name }}
