apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongoExpress.name }}
  labels:
    app: {{ .Values.mongoExpress.name }}
spec:
  replicas: {{ .Values.mongoExpress.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mongoExpress.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongoExpress.name }}
    spec:
      containers:
        - name: {{ .Values.mongoExpress.name }}
          image: {{ .Values.mongoExpress.image.repository }}:{{ .Values.mongoExpress.image.tag }}
          ports:
            - containerPort: {{ .Values.mongoExpress.service.port }}
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: {{ .Values.mongodb.name }}
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.name }}-secret
                  key: mongodb-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.name }}-secret
                  key: mongodb-root-password
